# Generated by Django 4.1 on 2022-11-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_rename_userid_teacher_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacherCode',
            new_name='fullName',
        ),
    ]
