# Generated by Django 4.1 on 2022-11-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.group')),
            ],
        ),
    ]
