# Generated by Django 4.1 on 2022-11-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectMajor', '0001_initial'),
        ('sectionClass', '0002_remove_sectionclass_subjectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='subjectMajor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectMajor.subjectmajor'),
        ),
    ]
