# Generated by Django 4.1 on 2022-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionClass', '0003_alter_sectionclass_subjectmajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionclass',
            name='dayAdd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='dayDefault',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='dayEnd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='dayLessonList',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='quanlityReal',
            field=models.IntegerField(null=True),
        ),
    ]
