# Generated by Django 4.1 on 2022-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionClass', '0004_sectionclass_dayadd_sectionclass_daydefault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='dayDefault',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
