# Generated by Django 4.1 on 2022-11-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TermMajorSubject', '0001_initial'),
        ('sectionClass', '0005_alter_sectionclass_daydefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionclass',
            name='termMajorSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TermMajorSubject.termmajorsubject'),
        ),
    ]
