# Generated by Django 4.1 on 2022-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Term', '0001_initial'),
        ('sectionClass', '0008_alter_sectionclass_daylessonlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionclass',
            name='termMajorSubject',
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Term.term'),
        ),
    ]
