# Generated by Django 4.1 on 2022-11-29 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectionClass', '0009_remove_sectionclass_termmajorsubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionclass',
            name='dayAdd',
        ),
        migrations.RemoveField(
            model_name='sectionclass',
            name='dayEnd',
        ),
        migrations.RemoveField(
            model_name='sectionclass',
            name='dayStart',
        ),
    ]
