# Generated by Django 4.1 on 2022-11-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionClass', '0010_remove_sectionclass_dayadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='dayLessonList',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
