# Generated by Django 4.1 on 2022-11-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0004_alter_student_fullname'),
        ('TermMajorSubject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('termMajorSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TermMajorSubject.termmajorsubject')),
            ],
        ),
    ]
