# Generated by Django 4.1 on 2022-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_userid_student_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fullName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
