# Generated by Django 4.1 on 2022-11-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='numberOfCredits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
