# Generated by Django 4.1 on 2022-11-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Term', '0001_initial'),
        ('SubjectMajor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermMajorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectMajor.subjectmajor')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Term.term')),
            ],
        ),
    ]
